// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyjoxzxtadduaqwtsbid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5am94enh0YWRkdWFxd3RzYmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3Mjk4NjQsImV4cCI6MjA3MTMwNTg2NH0.xKwrJ1-syubIndaJzD56b4mjGGqb42K9DpwaeEY9NSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});